meta:
  site_title: "CarterRabasa.com"
  site_subtitle: "This is my tech nook. There are many like it, but this one is mine."
  site_language: "en"
  absolute_baseurl: http://carter.rabasa.com
  domain: carter.rabasa.com
  author:
    full_name: Carter Michael Rabasa
    short_name: crabasa
    email: carter@rabasa.com

tag_dir: tag
pygments: true
markdown: rdiscount
permalink: pretty
